### ISSUE TITLE
怎么使用呀

### ISSUE THREAD

**Issue by mxdlsm** [xiangwangrush/jiaguplugin#1]

**Comment by xiangwangrush** [comment]
HI 你好
&nbsp; &nbsp; 那个插件很久没更新了，用的gradle版本还比较老旧。
&nbsp; &nbsp; 实现的功能非常简单，通过调用360加固助手提供的jar的几个API。可能当时插件代码里面没有注释具体调用的API，
&nbsp; &nbsp; 可以先下载360加固助手到本地,执行对于的jar命令 查看加固具体API。
&nbsp; &nbsp; 我发你一个文档，是之前的一个使用手册。
&nbsp; &nbsp; 如果gradle版本差别太大导致不兼容，可以尝试自己写一个gradle插件或者现在buildSrc下拷贝对应的文件进行调试即可。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiangwangrush/jiaguplugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月5日(星期三) 中午12:35
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xiangwangrush/jiaguplugin] 怎么使用呀 (Issue #1)





 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiangwangrush** [comment]
当时插件发布在jcenter上的，建议直接从github上下载代码后，放入buildSrc下使用吧。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiangwangrush/jiaguplugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月5日(星期三) 中午12:35
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xiangwangrush/jiaguplugin] 怎么使用呀 (Issue #1)





 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiangwangrush** [comment]
提交了使用手册ReadMe到master上

**Comment by mxdlsm** [comment]
谢谢
